# Generated by Django 2.1.5 on 2019-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
